CUDA_VISIBLE_DEVICES=1,2,3,4 \
torchrun --nproc_per_node=4 --master_port=4568 train.py \
    --model_name_or_path ../models/llama2-7b-hf/ \
    --data_path ./json4train/example.json \
    --bf16 True \
    --output_dir ../output/new-model/ \
    --num_train_epochs 3 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap offload" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --tf32 True \
    --gradient_checkpointing True
